// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP



#define SRS_AUTO_BUILD_DATE "2017-02-07 12:23:00"
#define SRS_AUTO_UNAME "legahero xie"
#define SRS_AUTO_USER_CONFIGURE "legahero xie"
#define SRS_AUTO_CONFIGURE "legahero xie"

#endif
